- apps/tradein-admin/src/app/pages/product-management/edit-product/index.tsx
This PR includes the following:
> Fix: URL Param Mapping

- apps/tradein-admin/src/app/pages/product-management/edit-product/index.tsx
- apps/tradein-admin/src/app/pages/user-management/add-user/index.tsx
- apps/tradein-admin/src/app/pages/user-management/index.tsx
- libs/src/store/product/actions.ts
- libs/src/store/product/use-product.ts
This PR includes the following:
> fix build errors - apply abort controller to edit product page

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/card-detail.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/device-section.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/status/edit-form.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- apps/tradein-admin/src/app/pages/order-management/index.tsx
- apps/tradein-admin/tailwind.config.js
- libs/src/components/button/copy-button.tsx
- libs/src/components/button/index.ts
- libs/src/components/loader/loader.tsx
- libs/src/components/modal/index.ts
- libs/src/components/modal/status-modal.tsx
- libs/src/components/navigation/top-navigation.tsx
- libs/src/constants/constants.tsx
- libs/src/store/auth/action-types.ts
- libs/src/store/auth/actions.ts
- libs/src/store/auth/reducer.ts
- libs/src/store/auth/use-auth.ts
- libs/src/store/globalReducer.ts
- libs/src/store/order/action-types.ts
- libs/src/store/order/actions.ts
- libs/src/store/order/reducer.ts
- libs/src/store/order/use-order.ts
**Updates:**
- Single order flow actions
- Update status dialog and validation
- Copy to clipboard button
- Revert Device assessment UI
> Feature: Order details Page

- apps/tradein-admin/src/app/pages/actionables/index.tsx
- libs/src/store/order/actions.ts
> update generate labels payload, url and response mapping

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/card-detail.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/device-section.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- apps/tradein-admin/tailwind.config.js
- libs/src/components/button/copy-button.tsx
- libs/src/components/styled/card.ts
> Update display of cards in order management

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/card-detail.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/device-section.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- libs/src/components/styled/card.ts
- libs/src/configs/order-management-config.tsx
- libs/src/helpers/helpers.tsx
- libs/src/helpers/index.ts
- libs/src/helpers/orders.tsx
**Updates**
- Update missing details in order management page
- Tweaked layout and spacing on mobile view
> [Order management] Fix missing details 

- apps/tradein-admin/src/app/pages/actionables/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- libs/src/store/order/actions.ts
- libs/src/store/order/use-order.ts
**Updates**
- Update payload for generating labels and sending boxes (for tablet and laptop)
- Update mapping of shipping details per order item
> [Order management] Update in generating labels and mapping of shipment

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- libs/src/constants/enums.ts
- libs/src/store/order/actions.ts
**Updates**
- Handle multiple shipments per order item
- Update parsing of response for printing labels
> [Orders] Update handling of shipment and printing labels

- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- libs/src/components/button/button.tsx
- libs/src/components/button/index.ts
- libs/src/components/styled/card.ts
- libs/src/store/order/action-types.ts
- libs/src/store/order/actions.ts
- libs/src/store/order/reducer.ts
- libs/src/store/order/use-order.ts
> Feature: Gift Card Status

- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
- libs/src/configs/actionables-management-config.tsx
- libs/src/configs/order-management-config.tsx
- libs/src/configs/promotion-claims-management.tsx
- libs/src/configs/promotions-management-config.tsx
- libs/src/helpers/helpers.tsx
**Updates**
- Update date format to DD/MM/YYYY
> Update Order Details and date format

- libs/src/constants/constants.tsx
change memory to ram, and storage to size
> [main]fix/change attributes value

- libs/src/components/table/pagination.tsx
- libs/src/components/table/table.tsx
- libs/src/components/typography/typography.tsx
- libs/src/constants/constants.tsx
> added rows per page action

- apps/tradein-admin/src/app/pages/order-management/claims-list.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- libs/src/components/styled/card.ts
- libs/src/components/table/table.tsx
> Display list of claims in order details page

- apps/tradein-admin/src/app/pages/promotion-claims-management/index.tsx
- libs/src/configs/promotion-claims-management.tsx
> [CWLP2-23] Add count for multiple claim actions

- apps/tradein-admin/src/app/pages/promotion-claims-payments/index.tsx
> clear selected rows on submit claims payment

- libs/src/components/upload/upload.tsx
- libs/src/store/product/reducer.ts
> [WL2-261] fix file select bug and fix table loading state after submit upload file

- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
- cancel voucher [change to voucher?.itemNumber]
> [MAIN]hotfix/change to voucher order number

- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
- libs/src/store/order/actions.ts
-change endpoint in cancel voucher and params to voucherPan
> [MAIN]hotfix/change endpoint in cancel voucher

- libs/src/components/menu/menu.tsx
> Fix: WL2-341

- libs/src/components/table/table.tsx
- libs/src/configs/product-upload-logs-config.tsx
- libs/src/configs/promotion-claims-management.tsx
> update table configs and adjust table spacing

- libs/src/components/navigation/side-navigation.tsx
- libs/src/constants/constants.tsx
> added templates to sidebar

- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/device-section.tsx
- add copy to clipboard button in Product name
> CWLP2-163: Copy to clipboard on product name

- apps/tradein-admin/src/app/pages/promotion-claims-management/forms/bulk-update-claims.tsx
- apps/tradein-admin/src/app/pages/promotion-claims-management/index.tsx
- libs/src/store/promotion/actions.ts
- libs/src/store/promotion/use-promotion.ts
> [CWLP2-134] bulk-update-moorup-status

- libs/src/configs/product-upload-logs-config.tsx
- libs/src/constants/constants.tsx
- libs/src/constants/enums.ts
- libs/src/helpers/helpers.tsx
- libs/src/store/product/actions.ts
> [CWLP2-167] Added Upload Type Column to Product Upload Logs Table

- apps/tradein-admin/src/app/pages/template-approvals/template-approval-item/index.tsx
> fix payload for template change approval

- apps/tradein-admin/src/app/pages/actionables/index.tsx
return previous filter in actionables
> [MAIN]hotfix/actionables filter

- apps/tradein-admin/src/app/pages/actionables/index.tsx
added printLabelAction and returnDeviceAction in actionables
https://moorupau.atlassian.net/jira/servicedesk/projects/MTS/queues/custom/5/MTS-1009
> [MAIN]hotfix/added printLabelAction and returnDeviceAction in actionables

- apps/tradein-admin/src/app/pages/actionables/index.tsx
https://moorupau.atlassian.net/browse/MTS-1009
> [MAIN]hotfix/filter only tablets and laptops in actionables

- apps/tradein-admin/src/app/pages/payments/index.tsx
- libs/src/store/order/action-types.ts
- libs/src/store/order/actions.ts
- libs/src/store/order/reducer.ts
- libs/src/store/order/use-order.ts
> CWLP2-192: Added button to download flatfile

- apps/tradein-admin/src/app/pages/actionables/followup-unsent-device/modal-content.tsx
- libs/src/store/order/action-types.ts
- libs/src/store/order/actions.ts
- libs/src/store/order/use-order.ts
> [CWLP2-200] Update API config for unsent device actions

- apps/tradein-admin/src/app/pages/actionables/followup-unsent-device/modal-content.tsx
- apps/tradein-admin/src/app/pages/actionables/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- libs/src/store/order/actions.ts
- libs/src/store/order/use-order.ts
> added admin_id to payload

- libs/src/store/auth/actions.ts
- libs/src/store/auth/use-auth.ts
- libs/src/store/order/actions.ts
- libs/src/store/order/use-order.ts
- libs/src/store/product/actions.ts
- libs/src/store/product/use-product.ts
- libs/src/store/promotion/actions.ts
- libs/src/store/promotion/use-promotion.ts
- libs/src/store/templates/actions.ts
- libs/src/store/templates/use-template.ts
- libs/src/store/user/actions.ts
- libs/src/store/user/use-user.ts
This PR includes the following:
> added bearer token to axios instance

- apps/tradein-admin/src/app/pages/actionables/index.tsx
- libs/src/components/table/table.tsx
> [UAT] added 2 filter buttons in actionables

- apps/tradein-admin/src/app/pages/actionables/followup-recycle-offer/modal-content.tsx
- apps/tradein-admin/src/app/pages/actionables/followup-revision-offer/modal-content.tsx
- apps/tradein-admin/src/app/pages/actionables/followup-unsent-device/modal-content.tsx
Updates:
- CWLP2-255: Fix status display for Previously Extended revision offers
- CWLP2-257: Fix labels for dialogs in Follow-up Recycle Offer page
> CWLP2-255, 256: Previously extended status

- libs/src/constants/constants.tsx
> CWLP2-261: Update label for tabs in actionable print label action

- apps/tradein-admin/src/app/pages/actionables/locked-devices-for-retest/index.tsx
> CWLP2-260: Added option "Remain Locked" in Locked Devices for retest

- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/shipping-section.tsx
> CWLP2-285: Added outbound tracking details

- apps/tradein-admin/src/app/pages/order-management/edit-order/index.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/status/edit-form.tsx
> Added device assessment option and fix computation

- apps/tradein-admin/src/app/pages/order-management/index.tsx
added clearOrder in onRowClick to clear the previous order state
https://github.com/user-attachments/assets/a66251cd-49f9-42b1-b95d-4f032fe59b19
> [MAIN] hotfix/added onRowClick to order table component

- libs/src/constants/constants.tsx
- libs/src/constants/enums.ts
aligned -> Completion
revised -> Validation & Offer
for-recycle -> Validation & Offer
recycled -> Completion
for-return -> Validation & Offer
returned -> Completion
> [UAT] fix/update order item status

- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
https://moorupau.atlassian.net/jira/servicedesk/projects/MTS/issues/MTS-2100?jql=project%20%3D%20MTS%20ORDER%20BY%20key%20DESC%2C%20%22Time%20to%20resolution%22%20ASC
> [MAIN] hotfix/added address line 2 to completeAddress

- libs/src/store/order/actions.ts
> [MAIN] hotfix/set voucherOrderNumber as query parameter in refresh GC EP

- apps/tradein-admin/src/app/pages/dashboard/index.tsx
- libs/src/components/component-wrapper/public-route.tsx
- libs/src/components/component-wrapper/wrapper.tsx
- libs/src/components/modal/announcement-modal.tsx
- libs/src/components/modal/index.ts
- libs/src/constants/constants.tsx
- libs/src/store/auth/actions.ts
> [UAT] feature/show announcement popup after login

- libs/src/constants/constants.tsx
- libs/src/constants/enums.ts
> [UAT] fix/moved revision-accepted/rejected in COMPLETION tab in OMC

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
> [UAT] fix/added grid in order item card

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
- apps/tradein-admin/src/app/pages/order-management/index.tsx
- libs/src/configs/actionables/actionables-device-credit-charge-needed.tsx
> [UAT] fix/payment action needed (change from sort to filter by status='for-charge')

- apps/tradein-admin/src/app/pages/actionables/devices-for-inventory/index.tsx
- libs/src/configs/actionables/actionables-devices-for-inventory.tsx
- libs/src/constants/table-columns.tsx
-change order number to imei/serial and removed customer name
-filter order items by status !== aligned, revision-accepted, recycled, and returned
> [UAT] fix/change order number to imei/serial and removed customer name

- apps/tradein-admin/src/app/pages/actionables/devices-for-inventory/index.tsx
> [UAT] fix/exclude 'returned' status from addActions filter

- apps/tradein-admin/src/app/pages/order-management/edit-order/collection.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/completion.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/card-detail.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/validation-offer.tsx
https://moorupau.atlassian.net/browse/MTS-2258?atlOrigin=eyJpIjoiY2U1OGZmZjllZjNhNDExNzhiM2Q2MWZkZTg5NjAzM2YiLCJwIjoiaiJ9
> [MAIN] hotfix/remove scrollbar in order item card

- libs/src/configs/actionables/actionables-management-config.tsx
> [UAT] fix/change Status to Order Item Status in Devices With Box

- apps/tradein-admin/src/app/pages/promotion-claims-management/index.tsx
> added confirmation modal for remove attachment

- apps/tradein-admin/src/app/pages/promotion-claims-management/index.tsx
- libs/src/components/menu/dropdown.tsx
> update dropdown component behavior

- apps/tradein-admin/src/app/pages/actionables/devices-for-return/index.tsx
added toast notification and printOutboundLabel functionality to DevicesForReturnPage
> [MAIN] hotfix/added printOutboundLabel to Devices for Return

- apps/tradein-admin/src/app/pages/promotions/add-promotion-eligibility-and-faqs/index.tsx
- apps/tradein-admin/src/app/pages/promotions/index.tsx
- hide side modal when clicking preview button
- show side modal when clicking close button in preview button
> [UAT] fix create promotion side modal state

- libs/src/constants/constants.tsx
- libs/src/constants/enums.ts
- libs/src/helpers/helpers.tsx
**Updated Status Labels:**
Changed revision-accepted to **accepted**. (Order Item Status)
Changed processing to **in-progress**. (Order Status)
Changed completed to **closed**. (Order Status)
> [UAT] Update constants and enums for order status and item status

- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
ticket: https://moorupau.atlassian.net/browse/BAU-64
- Update voucher provider check in quote details component to include multiple providers (retravision)
> [BAU-64] hotfix/display voucher status for Retravision GCs

- libs/src/components/component-wrapper/public-route.tsx
- libs/src/components/input/date-range-picker/date-range-picker.tsx
> [MIPP-406] Fix OMC build errors

- apps/tradein-admin/src/app/pages/promotions/add-promotion-claims/index.tsx
- apps/tradein-admin/src/app/pages/promotions/add-promotion/index.tsx
- apps/tradein-admin/src/app/pages/promotions/index.tsx
- apps/tradein-admin/src/app/pages/promotions/preview-content/index.tsx
- libs/src/constants/constants.tsx
- libs/src/constants/enums.ts
NEW CREATE PROMOTION TYPE FIELD
> [MIPP-404] - Add new promotion type & condition renders

- apps/tradein-admin/src/app/pages/payments/index.tsx
https://moorupau.atlassian.net/browse/BAU-77
> [BAU-77] hotfix/show device summary only to moorup and costco

- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/offer-section.tsx
- libs/src/constants/constants.tsx
- add new subheading and Device payment status
> [dev] - Add Device Payment Status on device card

- apps/tradein-admin/src/app/pages/actionables/devices-with-box/index.tsx
- libs/src/configs/actionables/actionables-management-config.tsx
- libs/src/constants/enums.ts
> [MIPP-492] Update query filters and update table config

- apps/tradein-admin/src/app/pages/order-management/edit-order/quote-details.tsx
- apps/tradein-admin/src/app/pages/order-management/edit-order/sections/card-detail.tsx
- libs/src/components/button/copy-button.tsx
- libs/src/components/navigation/side-navigation.tsx
- libs/src/components/styled/badge.ts
- libs/src/constants/constants.tsx
- libs/src/helpers/helpers.tsx
> Feature/mipp 520 521 update sidebar and UI
